{% set name = "fast-cdr" %}
{% set version = "1.0.15" %}
{% set major_minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eProsima/Fast-CDR/archive/v{{ version }}.tar.gz
    sha256: e09ce013b4fbbee11ad0ac3a17ef5e55376f2c7a3696e4d5cd0ff696519fe486

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\fastcdr-{{ major_minor_version }}.dll exit 1  # [win]
    - test -f $PREFIX/lib/libfastcdr${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libfastcdr${SHLIB_EXT}.{{ version }}  # [linux]
    - test -f $PREFIX/include/fastcdr/Cdr.h  # [unix]

about:
  home: https://github.com/eProsima/Fast-CDR
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    eProsima FastCDR

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
